version: '3'
services:
  training-neo4j:
    image: neo4j:4.0.6-enterprise
    container_name: "link-prediction-neo4j"
    volumes:
      - ./plugins:/plugins
      - ./data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/admin"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*"
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]

  training-jupyter:
    container_name: "link-prediction-jupyter"
    image: jupyter/scipy-notebook:${JUPYTER_VERSION:-latest}
    volumes:
      - ./notebooks:/home/jovyan
    ports:
      - "8888:8888"
    environment:
      - "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
      - "ACCESS_ID=${ACCESS_ID}"
      - "ACCESS_KEY=${ACCESS_KEY}"
      - "SAGEMAKER_ROLE=${SAGEMAKER_ROLE}"
